package com.tienda.electronicos.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class AssetTableInitializer {

    private static final Logger log = LoggerFactory.getLogger(AssetTableInitializer.class);
    private final JdbcTemplate jdbc;

    public AssetTableInitializer(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    public void init() {
        try {
            Integer count = jdbc.queryForObject(
                    "SELECT COUNT(*) FROM user_tables WHERE table_name = 'ASSET'",
                    Integer.class
            );

            if (count == null || count == 0) {
                log.info("Tabla ASSET no encontrada. Creando tabla ASSET...");
                String sql = "CREATE TABLE ASSET ("
                        + "ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,"
                        + "FILENAME VARCHAR2(255) NOT NULL,"
                        + "PATH VARCHAR2(4000),"
                        + "CONTENT BLOB,"
                        + "CONTENT_TYPE VARCHAR2(255),"
                        + "SIZE NUMBER,"
                        + "CREATED_AT TIMESTAMP WITH TIME ZONE"
                        + ")";
                jdbc.execute(sql);
                jdbc.execute("CREATE INDEX IDX_ASSET_FILENAME ON ASSET(FILENAME)");
                log.info("Tabla ASSET creada correctamente.");
            } else {
                log.info("Tabla ASSET ya existe en la BD.");
            }
        } catch (Exception e) {
            log.warn("No se pudo comprobar/crear la tabla ASSET: {}", e.getMessage());
        }
    }
}

