package com.tienda.electronicos.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseSchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaInitializer.class);
    private final JdbcTemplate jdbc;

    public DatabaseSchemaInitializer(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    public void init() {
        checkAndCreateImagenUrlColumn();
        checkAndCreatePaymentTransactionTable();
    }

    private void checkAndCreateImagenUrlColumn() {
        try {
            Integer count = jdbc.queryForObject(
                    "SELECT COUNT(*) FROM user_tab_columns WHERE table_name = 'PRODUCTO' AND column_name = 'IMAGEN_URL'",
                    Integer.class
            );

            if (count == null || count == 0) {
                log.info("Columna IMAGEN_URL no encontrada en PRODUCTO. Intentando crear columna...");
                try {
                    jdbc.execute("ALTER TABLE producto ADD imagen_url VARCHAR2(500)");
                    log.info("Columna IMAGEN_URL creada correctamente en PRODUCTO.");
                } catch (Exception e) {
                    log.warn("No se pudo crear la columna IMAGEN_URL: {}", e.getMessage());
                }
            } else {
                log.info("Columna IMAGEN_URL ya existe en PRODUCTO.");
            }
        } catch (Exception e) {
            log.warn("Error comprobando columna IMAGEN_URL en PRODUCTO: {}", e.getMessage());
        }
    }

    private void checkAndCreatePaymentTransactionTable() {
        try {
            Integer count = jdbc.queryForObject(
                    "SELECT COUNT(*) FROM user_tables WHERE table_name = 'PAYMENT_TRANSACTION'",
                    Integer.class
            );

            if (count == null || count == 0) {
                log.info("Tabla PAYMENT_TRANSACTION no encontrada. Intentando crear tabla...");
                try {
                    String sql = "CREATE TABLE payment_transaction ("
                            + "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,"
                            + "reference VARCHAR2(100) UNIQUE,"
                            + "amount NUMBER(19,2),"
                            + "currency VARCHAR2(10),"
                            + "status VARCHAR2(30),"
                            + "buyer_email VARCHAR2(200),"
                            + "pse_transaction_id VARCHAR2(200),"
                            + "pse_bank_code VARCHAR2(50),"
                            + "redirect_url VARCHAR2(1000),"
                            + "created_at TIMESTAMP WITH TIME ZONE,"
                            + "updated_at TIMESTAMP WITH TIME ZONE"
                            + ")";
                    jdbc.execute(sql);
                    jdbc.execute("CREATE INDEX IDX_PAYMENT_REF ON payment_transaction(reference)");
                    log.info("Tabla PAYMENT_TRANSACTION creada correctamente.");
                } catch (Exception e) {
                    log.warn("No se pudo crear la tabla PAYMENT_TRANSACTION: {}", e.getMessage());
                }
            } else {
                log.info("Tabla PAYMENT_TRANSACTION ya existe.");
            }
        } catch (Exception e) {
            log.warn("Error comprobando la tabla PAYMENT_TRANSACTION: {}", e.getMessage());
        }
    }
}

