-- Script para crear la tabla ASSET en Oracle
-- Ejecutar como el schema/usuario conectado a la base de datos configurada en application.properties

CREATE TABLE ASSET (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FILENAME VARCHAR2(255) NOT NULL,
    PATH VARCHAR2(4000),
    CONTENT BLOB,
    CONTENT_TYPE VARCHAR2(255),
    SIZE NUMBER,
    CREATED_AT TIMESTAMP WITH TIME ZONE
);

-- Índice para búsquedas por filename (opcional)
CREATE INDEX IDX_ASSET_FILENAME ON ASSET(FILENAME);

